### ISSUE TITLE
Error reading: Wrong string hash persist.roster

### ISSUE THREAD

**Issue by DarkestMan1** [robojumper/DarkestDungeonSaveEditor#13]
I attempted to use this on my heavily modded save (with custom characters, character limit extenders, and new trinkets/ trinket slot extenders) and this happened. What seems to be the matter?

[persist.roster.zip](https://github.com/robojumper/DarkestDungeonSaveEditor/files/3338695/persist.roster.zip)

**Comment by robojumper** [comment]
https://github.com/robojumper/DarkestDungeonSaveEditor/blob/50c28e9058a18896235fa9c1bc310f70c64a2652/src/main/java/de/robojumper/ddsavereader/file/DsonFile.java#L116-L118

This file contains a field with a name that mismatches the hash specified in the save file header. The decoder rejects the file in order to minimize potential errors from parsing data the wrong way.

There is a chance that I'm getting the string encoding wrong. I'll look into 1) finding the erroneous field and fixing the error if it's on my side and 2) making the error message more useful.

**Comment by DarkestMan1** [comment]
Oh, that makes sense. Alright, thank you for responding so quick man! You're awesome!

**Comment by robojumper** [comment]
#14 fixes this. This is in fact an error on my side, where I implicitly assumed that field names were ASCII. However, the [Conquerer](https://steamcommunity.com/sharedfiles/filedetails/?id=1759328270) mod (which I assume you're using) contains skills like `stärke`, which the decoder (and encoder) couldn't handle.

The fix is up, but I'll think it over and cut a release in the next few days.

**Comment by DarkestMan1** [comment]
Thanks man! Yeah I am using it. That's interesting to know that that's the reason why things went kaput.
