### ISSUE TITLE
Add Python/C hasher solutions to docs.

### ISSUE THREAD

**Issue by CinnamonKilljoy** [robojumper/DarkestDungeonSaveEditor#60]
Hello! First, thanks for your work; the save editor is has been really helpful for my own hobby-modding. I've used it extensively and am super happy that it exists. :)

In my own modding I use a code base that reads game files, modify them in runtime, and then write the modified content to new files.
I do this in _Python_ (mostly to practice it since I'm more into compiled languages) and that was all well and good, until I ran into trying to figure out how on earth to get the "tree_id" numbers for persist.upgrades.json. After a while I found the Java hashing function in this repo in docs/dson.md.

Now, Python gets a bit stupid when it comes to managing unsigned/signed juggling back and forth, so it took me a bit of time to understand how to get it to work. The solution essentially just uses C in Python to make it work, so it's not difficult. But I figured that I might not be the first nor the last person who'll end up here when trying to get the hasher function to work. So if you feel it appropriate, you could add an example Python solution to the docs.

I mostly thought this a good idea since Python is pretty damn popular and the information sources for DD modding aren't too many, especially not on things like these.

I tried appending the .py file but github doesn't like that, so I'll just paste my solutions here:

<details>
<summary>Using built-in ctypes</summary>
<br>

      import ctypes

      def strash(string):
        """
          Darkest Dungeon hashing function.

          @note `int` can be used for `result`, but has to be cast to `uint` when returned in that case.

          @param  string  The string to hash.
          @return         The hash value of `string`.
        """

        constant  = ctypes.c_uint(53)
        result    = ctypes.c_uint(0)

        for char in string.encode("ascii"):
          result = ctypes.c_uint(
            result.value * constant.value + ctypes.c_uint(char).value
          )
        return result.value

</details>

<details>
<summary>Using external cffi library to compile C function.</summary>
<br>

      # pip install cffi
      from cffi import FFI

      def strash2(string):
        """
          Darkest Dungeon hashing function.
          
          @note Compiles a C function and executes that; slower.

          @param  string  The string to hash.
          @return         The hash value of `string`.
        """

        ffi = FFI()

        # C definition.
        ffi.set_source("_strash_C", """

      unsigned int strash(const char string[], const unsigned int length) {
        int result = 0;
        for (unsigned int index = 0; index < length; ++index) {
          result = result * 53 + ((unsigned int) string[index]);
        }
        return result;
      }

      """)

        # C *declaration*.
        ffi.cdef("""unsigned int strash(const char[], const unsigned int);""")
        ffi.compile()

        # Name is the same as `module_name`, 1st argument to `ffi.set_source`.
        from _strash_C import lib

        # Explicit ascii encoding due to no implicit encoding of arguments.
        return lib.strash(string.encode("ascii"), len(string))

</details>

All the best!

**Comment by robojumper** [comment]
Hey, glad to hear you're finding this useful. I think I can comment a bit on the hashing thing.

First of all, it actually doesn't matter if you use signed arithmetic or unsigned arithmetic - two's complement ensures that addition behaves the same whether it's signed or unsigned, and even multiplication is the same for the lower 32 bits of the result (you can verify this for example with the [Rust implementation](https://rust.godbolt.org/z/c7ova68P9) - the generated machine code and the bytes of the hash each are the exact same). The only difference is in the textual JSON output, since the interpretation of the result will be different.

So the Java code simply used signed ints because that's the 32-bit integer type in Java, but if there was wrapping unsigned 32-bit arithmetic I could've used that and it would have worked fine. But since I had decoded ints before I even discovered the fact that there are hashes I used signed ints and here we are.

> Explicit ascii encoding due to no implicit encoding of arguments.

This is a quite unfortunate situation - I've observed mods with UTF-8 strings and the game hashed that UTF-8 encoded string, but the game may also generate invalid UTF-8 in situations like #27. The "correct" solution here is to completely give up on Unicode string encodings and treat all strings as byte buffers that may or may not be encoded strings but I hated that idea and ignored the problem. UTF-8 might work a bit better in cases where mods are involved...

> compile C function

Your C function exhibits Undefined Behavior (UB) because in C, signed arithmetic overflow is UB yet you rely on wrapping arithmetic.

If I may offer a solution, I would recommend something like this, which exploits the fact that wrapping 32-bit two's complement arithmetic doesn't care about signs:

```python
def strhash(string):
    result = 0
    for char in string.encode("utf-8"):
        result = (((result * 53) & 0xFFFFFFFF) + char) & 0xFFFFFFFF

    return (result ^ 0x80000000) - 0x80000000


assert strhash("ieufhop9a2847oaxhdnladfelfeif") == -876057725
print("Ok")
```
this produces the exact same signed result in Python as the Java and Rust implementations - try going to [my online implementation of the editor](https://robojumper.github.io/DarkestDungeonSaveEditor/) and use the "hash utility" at the bottom to verify this.

Hope this helps!
